# Generated by Django 5.0.3 on 2024-03-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')]),
        ),
    ]
