# Generated by Django 5.0.3 on 2024-03-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
    ]
